# Generated by Django 5.0.7 on 2024-07-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="crudparts",
            fields=[
                (
                    "cod",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(max_length=50)),
                ("equipamento", models.CharField(max_length=50)),
            ],
        ),
    ]
